name: Salesforce Deployment

on:   
  push:
    branches:
      - 'feature/*'
      - 'release/*'
    paths-ignore: 
      - 'README.md' 
      - '.github/**'

jobs:
   deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        
      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli     
      
 
      - name: Authenticate with Salesforce
        run: | 
             echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL1 }}" > sfdxurl1.txt
             sfdx force:auth:sfdxurl:store -f sfdxurl1.txt -a devop29jun
                 

      - name: Deploy to Salesforce (Feature Branch)
        if: startsWith(github.ref, 'refs/heads/feature/')      
        run: |                 
            sfdx force:source:deploy -c -p "force-app" -u devop29jun --verbose --ignorewarnings

      - name: Deploy to Salesforce (Release Branch)
        if: startsWith(github.ref, 'refs/heads/release/')
        run: | 
            sfdx force:source:deploy -c -p "force-app" -u devop29jun --verbose --ignorewarnings            