name: Salesforce Deployment

on:   
  push:
    branches:
      - 'feature/*'
      - 'release/*'
    paths-ignore: 
      - 'README.md' 
      - '.github/**'

jobs:
   deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        
      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          sfdx-version: latest
          vlocity-version: latest   
      
 
      - name: Authenticate with Salesforce
        env:
           SFDX_AUTH_URL2: ${{ secrets.SFDX_AUTH_URL2 }}
        run: | 
             echo ''${{ secrets.SFDX_AUTH_URL2 }}'' > sfdxurl1.txt
             sfdx force:auth:sfdxurl:store -f sfdxurl1.txt -a devop29jun
                 

      - name: Deploy to Salesforce (Feature Branch)
        if: startsWith(github.ref, 'refs/heads/feature/')      
        run: |
            sfdx vlocityestools:sfsource:createdeltapackage -u devop29jun -p cmt -d force-app -c GeneralSettings__c -v VBTDeployKey_SF
            if [ -d force-app_delta ]; then
            echo "Running the Deployment"                        
            sfdx force:source:deploy -c -p "force-app_delta" -u devop29jun --verbose --ignorewarnings
            head_commit=$(git rev-parse HEAD)
            sfdx force:data:record:update -s GeneralSettings__c  -w "Name='VBTDeployKey_SF'" -v "Value__c='$head_commit'" -u devop29jun

      - name: Deploy to Salesforce (Release Branch)
        if: startsWith(github.ref, 'refs/heads/release/')
        run: | 
            sfdx vlocityestools:sfsource:createdeltapackage -u devop29jun -p cmt -d force-app -c GeneralSettings__c -v VBTDeployKey_SF
            if [ -d force-app_delta ]; then
            echo "Running the Deployment"
            sfdx force:source:deploy -c -p "force-app_delta" -u devop29jun --verbose --ignorewarnings            